# reference: https://www.youtube.com/watch?v=tGYNYPKTyno
#reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html

AWSTemplateFormatVersion: "2010-09-09"

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06e46074ae430fba6 
      InstanceType: t2.medium
      KeyName: demon
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y git 
          sudo yum install nginx -y
          curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
          sudo yum install -y nodejs
          
          sudo git clone https://github.com/rituraj567/cloudprojectfrontend
          cd cloudprojectfrontend
          sudo npm install
          sudo npm run build
          sudo rm -rf /usr/share/nginx/html/*
          sudo cp -r build/* /usr/share/nginx/html/
          sudo systemctl start nginx
          sudo systemctl enable nginx
     

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access to EC2 instances
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
